services:
  # esoft_mtg:
  #   container_name: 'esoft_mtg'
  #   build:
  #     context: .
  #     dockerfile: ./Dockerfile
  #   restart: always
  #   depends_on:
  #     - db_esoft_mtg
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - ENV=production
  #     - BASE_URL=http://esoft_mtg:3000
  #     - JWT_SECRET=38b060a751ac96384cd9327eb1b1e36a21fdb71114be07434c0cc7bf63f6e1da274edebfe76f65fbd51ad2f14898b95b
  #     - DATABASE_URL=postgres://esoft_mtg:esoft_mtg@db_esoft_mtg:5432/esoft_mtg

  db_esoft_mtg:
    container_name: 'db_esoft_mtg'
    image: 'postgres:16.4-alpine'
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'esoft_mtg'
      POSTGRES_PASSWORD: 'esoft_mtg'
      POSTGRES_DB: 'esoft_mtg'
